displayName: Manual Access Control
type: middleware
iconPath: .assets/icon.png

import: github.com/iloahz/traefik-plugin-manual-access-control

summary: 'Provide manual access control for Traefik'

testData:
  Key: 8HvPVByYKFAt16+qG5/ZDgV11iVEDPOxVrM+caF81jA=
